//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corona_information
    {
        public string member_id { get; set; }
        public Nullable<System.DateTime> t_positive_answer { get; set; }
        public Nullable<System.DateTime> recovery_date { get; set; }
        public Nullable<int> id_vaccination_1 { get; set; }
        public Nullable<int> id_vaccination_2 { get; set; }
        public Nullable<int> id_vaccination_3 { get; set; }
        public Nullable<int> id_vaccination_4 { get; set; }
    
        public virtual Vaccination Vaccination { get; set; }
        public virtual Vaccination Vaccination1 { get; set; }
        public virtual Vaccination Vaccination2 { get; set; }
        public virtual Vaccination Vaccination3 { get; set; }
        public virtual Member Member { get; set; }
    }
}
